### PR TITLE
Fix markdown issues and add linter to CI pipeline

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `markdownlint -f --disable MD004 MD013 MD033 MD036 MD042 -- **/*.md`

See a detailed description of the rules is available at https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md

### CODE REVIEW

**Review by sunshowers — CHANGES_REQUESTED** [review]
Thanks for the contribution!

This looks like a very large change in terms of blame attribution, and it's not clear to me what the benefit of this is. Can the configuration be changed to minimize the diff?

For example, https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md004---unordered-list-style -- the unordered list style can be specified to be `:asterisk` so that the lines with `*` aren't converted to `-` unnecessarily.

This will also need CI support so that it doesn't regress in the future.

**Comment by kianmeng** [comment]
Let me revise this to minimize change and get back to you.

**Comment by kianmeng** [comment]
@sunshowers I've updated the changes to minimize the changes without polluting the blame attribution. However, I'm not sure if this change has any benefits besides improved readability.

Let me know if you prefer this change, and I'll continue with adding a job for CI. Otherwise, it's okay to reject this.

**Comment by sunshowers** [comment]
Hi @kianmeng -- apologies for missing this earlier. This looks good. Please add a CI job and we can land this. Thanks!

**Comment by kianmeng** [comment]
@sunshowers I've added the Markdown linter to the CI pipeline, let me know if there are anything else? Thanks.

**Comment by sunshowers** [comment]
Thank you!

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
